name: money_manager
description: "MoneyManager, an expense recording app that allows users to record their dialy expenses."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/svg/


  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf

